apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret
  namespace: prod
spec:
  provider:
    gcpsm:
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcp-secret
            key: credentials
            namespace: prod
      projectID: eco-seeker-442609-p7 # this is custom value
                    