apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
spec:
  clusterName: demo-nodejs
  git: 
    syncRepo: https://github.com/Gourav-91/nodejs-demo
    syncBranch: main
    policyDir: manifests
    syncWait: 10s