apiVersion: configsync.gke.io/v1
kind: RepoSync
metadata:
  name: repo-sync
  namespace: prod
spec:
  #applySpecVersion: v1alpha1
  sourceFormat: unstructured
  git:
    repo: https://github.com/Gourav-91/nodejs-demo.git
    branch: main
    dir: manifests/
    auth: none
