apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql
  namespace: prod
spec: 
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret
  target:
    name: postgresql
    creationPolicy: Owner
  dataFrom: 
  - extract:
      key: db-password